const data = {
    products: [
        {
            _id: 1,
            name: 'Metro 2035',
            category: 'Littérature',
            image: '/asset/Products/Metro2035.jpg',
            price: 9.99,
            form: 'Dmitry Glukhovsky',
            rating: 4.5,
            numReviews: 10,
            description: 'Le dernier chapitre de la saga Metro',
        },
        {
            _id: 2,
            name: "Zack Snyder's Justice League",
            category: 'Blu-ray',
            image: "/asset/Products/ZSJusticeLeague.jpeg",
            price: 29.99,
            from: 'Zack Snyder',
            rating: 4,
            numReviews: 15,
            description: 'Version de 4h fidèle à la vision du réalisateur et réclamée par les fans',
        },
        {
            _id: 3,
            name: 'The Last of Us Part II',
            category: 'Jeux vidéo',
            image: '/asset/Products/TLOU2.jpeg',
            price: 39.99,
            from: 'Naughty Dog',
            rating: 4.5,
            numReviews: 20,
            description: "Le GOTY de l'année 2020",
        },
        {
            _id: 4,
            name: 'Apple Watch Series 6 (GPS, 44 mm) Boîtier en Aluminium Gris sidéral, Bracelet Sport Noir',
            category: 'High-tech',
            image: '/asset/Products/AppleWatch.jpg',
            price: 399.99,
            from: 'Apple',
            rating: 5,
            numReviews: 100,
            description: 'La meilleure montre connectée du marché',
        },
        {
            _id: 5,
            name: 'Google Chromecast: Boitier Multimedia pour Streaming',
            category: 'High-tech',
            image: '/asset/Products/Chromecast.jpg',
            price: 39,
            from: 'Google',
            rating: 4.5,
            numReviews: 50,
            description: "Vos divertissements sur grand écran",
        },
        {
            _id: 6,
            name: 'Dans la Combi de Thomas Pesquet',
            category: 'Littérature',
            image: '/asset/Products/ThomasPesquet.jpg',
            price: 19.99,
            from: 'Marion Montaigne',
            rating: 3.5,
            numReviews: 2,
            description: "Le 2 juin 2017, le Français Thomas Pesquet, 38 ans, astronaute, rentrait sur Terre après avoir passé 6 mois dans l'ISS",
        },
        {
            _id: 7,
            name: 'Mad Max Anthology',
            category: 'Blu-ray',
            image: '/asset/Products/MadMax.jpg',
            price: 29.99,
            from: 'George Miller',
            rating: 5,
            numReviews: 25,
            description: 'Quatre film culte dans un seul coffret',
        },
        {
            _id: 8,
            name: 'Xbox Series S | La nouvelle Xbox 100% digitale | Compatible 4K HDR',
            category: 'Jeux vidéo',
            image: '/asset/Products/XboxSeriesS.jpg',
            price: 299.99,
            from: 'Microsoft',
            rating: 4,
            numReviews: 20,
            description: 'La console Next-gen la plus compacte et abordable du marché',
        }
    ]
};

export default data